### ISSUE TITLE
一部答えが含まれてしまう問題が出題される

### ISSUE THREAD

**Issue by hivesbee** [michimani/amazon-aws#1]
## 事象
[公式ドキュメント](https://docs.aws.amazon.com/) にてサービス名が長い場合、カッコ書きで略称が振られている場合があります（例えば以下などです）。
そしてそのカッコ書きが含まれた状態で出題されているかと思います。

- [Simple Email Service (Amazon SES)](https://docs.aws.amazon.com/ses/?id=docs_gateway)
- [Key Management Service (AWS KMS)](https://docs.aws.amazon.com/kms/?id=docs_gateway)

## 課題
カッコ書きまで含んだ状態で出題するとほぼほぼ答えが分かってしまいます。

## 提案
`(Amazon ...` や `(AWS ...` で始まる部分の文字列を削除する処理を入れてみてはどうでしょうか？

## P.S.
答えが分かっていたとしてもスコアは 4/10 でした。本当にありがとうございました。

**Comment by michimani** [comment]
ありがとうございます。 ご指摘の通り、カッコ書きで答えがわかってしまいますね...。  
ご提案頂いた方法による対処を検討致します。

**Comment by michimani** [comment]
@hivesbee   
お待たせいたしました。ヒントになり得るテキストを非表示にするようにしました。  
また、正解時にも正式名称を表示するようにしました。

**Comment by hivesbee** [comment]
@michimani 
手元でも確認できました！
おかげさまでスコアも 2/10 になりました！
ご対応ありがとうございました！
